const authDataLength = {
  EMAIL_MAX_LENGTH: 264,
  PASSWORD_MIN_LENGTH: 8,
  USERNAME_MAX_LENGTH: 32,
  USERNAME_MIN_LENGTH: 3,
  CLUBNAME_MAX_LENGTH: 32,
  CLUBNAME_MIN_LENGTH: 3,
}

export default authDataLength;